/**
 * Dish library, part three — the protein dishes
 * © 2026 Aseem Mohan. All rights reserved.
 *
 * INSTALL AT: lib/dishes-protein.js
 *
 * These ten exist for a different reason from the other thirty. Those are
 * teardowns of things people already eat. These are what to eat instead —
 * chosen for protein per calorie, and weighted towards non-vegetarian
 * because the rest of the library is almost entirely veg.
 *
 * They carry role: "solution", which the plan builder uses to surface them.
 *
 * DATA STATUS: ESTIMATES. NOT VERIFIED AGAINST IFCT 2017.
 */
export const PROTEIN_DISHES = [
  {
    id: "tandoori-chicken", name: "Tandoori chicken", category: "north",
    veg: false, verified: false, image: null, role: "solution",
    portion: "Half bird, 2 pieces on the bone",
    headline: "Forty-four grams of protein and almost no carbohydrate. One of the few restaurant dishes where the honest advice is order more of it.",
    components: [
      { name: "Chicken, on the bone", qty: "2 pieces", grams: 180, kcal: 300, carb: 0, protein: 42, fat: 14, fibre: 0,
        verdict: "good", note: "Cooked dry in a tandoor, not in a gravy. This is the most protein-dense thing on most Indian menus." },
      { name: "Yoghurt and spice marinade", qty: "—", grams: 40, kcal: 35, carb: 2, protein: 2, fat: 2, fibre: 0,
        verdict: "good", note: "Curd, ginger, garlic, chilli. Does all the flavour work for almost nothing." },
      { name: "Butter basting", qty: "~1 tbsp", grams: 12, kcal: 90, carb: 0, protein: 0, fat: 10, fibre: 0,
        verdict: "neutral", note: "Brushed on during and after cooking. Optional, and most kitchens will leave it off if asked." },
    ],
    tiers: [
      { level: 1, label: "Order it as it comes", saves: 0, tasteCost: "None",
        change: "Nothing. Forty-four grams of protein for around 425 calories.",
        why: "This is a dish that needs no fixing. If you are chasing a protein target and eating out, this is the order." },
      { level: 2, label: "Hold the butter", saves: 90, tasteCost: "Low",
        change: "Ask for it without the butter finish.",
        why: "The tandoor and the marinade carry the flavour. The basting is habit, not necessity." },
      { level: 3, label: "Air-fry it at home", saves: 90, tasteCost: "Moderate",
        change: "Same marinade, air fryer at 200°C.",
        why: "You lose the smoke, which is a real loss. You gain control over the fat and it costs a fifth as much." },
    ],
  },
  {
    id: "chicken-curry", name: "Chicken curry, home style", category: "north",
    veg: false, verified: false, image: null, role: "solution",
    portion: "1 katori chicken curry + 2 roti",
    headline: "This is what butter chicken should have been. Same bird, no cream, nearly twice the protein per calorie.",
    components: [
      { name: "Chicken", qty: "~150 g", grams: 150, kcal: 250, carb: 0, protein: 37, fat: 11, fibre: 0,
        verdict: "good", note: "Thirty-seven grams of protein. The reason to cook this." },
      { name: "Onion and tomato base", qty: "—", grams: 120, kcal: 65, carb: 12, protein: 2, fat: 1, fibre: 3,
        verdict: "good", note: "Slow-cooked onion is where the flavour comes from. It costs almost nothing." },
      { name: "Oil in the gravy", qty: "~1.5 tbsp", grams: 20, kcal: 175, carb: 0, protein: 0, fat: 20, fibre: 0,
        verdict: "driver", note: "The only real variable in the dish. A tablespoon is enough for four servings." },
      { name: "Roti", qty: "2 pieces", grams: 80, kcal: 240, carb: 46, protein: 8, fat: 2, fibre: 6,
        verdict: "neutral", note: "Fine as they are." },
    ],
    tiers: [
      { level: 1, label: "Halve the oil", saves: 90, tasteCost: "None",
        change: "Two teaspoons instead of a tablespoon and a half. Cook the onions longer.",
        why: "Time replaces fat in an onion base. This is the single most useful thing to learn in Indian cooking." },
      { level: 2, label: "More chicken, one roti", saves: 120, tasteCost: "None",
        change: "Bigger portion of curry, one roti instead of two.",
        why: "Pushes protein up and carbohydrate down without changing the dish at all." },
      { level: 3, label: "Skin off, thigh to breast", saves: 80, tasteCost: "Moderate",
        change: "Skinless breast rather than thigh on the bone.",
        why: "Leaner, though drier. Thigh tastes better and the difference is not large — this one is genuinely optional." },
    ],
  },
  {
    id: "egg-curry", name: "Egg curry", category: "north",
    veg: false, verified: false, image: null, role: "solution",
    portion: "2 eggs in gravy + 2 roti",
    headline: "The cheapest complete protein in Indian cooking. Then it gets cooked in three times the oil it needs.",
    components: [
      { name: "Eggs", qty: "2 whole", grams: 110, kcal: 155, carb: 1, protein: 13, fat: 11, fibre: 0,
        verdict: "good", note: "Complete protein, every essential amino acid, and cheaper per gram of protein than anything else here." },
      { name: "Onion and tomato gravy", qty: "1 katori", grams: 130, kcal: 70, carb: 12, protein: 2, fat: 1, fibre: 3,
        verdict: "good", note: "Nothing wrong with it." },
      { name: "Oil", qty: "~1.5 tbsp", grams: 20, kcal: 175, carb: 0, protein: 0, fat: 20, fibre: 0,
        verdict: "driver", note: "Often the largest single component, in a dish built around eggs." },
      { name: "Roti", qty: "2 pieces", grams: 80, kcal: 240, carb: 46, protein: 8, fat: 2, fibre: 6,
        verdict: "neutral", note: "Standard." },
    ],
    tiers: [
      { level: 1, label: "Cut the oil, add an egg", saves: 30, tasteCost: "None",
        change: "Two teaspoons of oil, three eggs instead of two.",
        why: "Costs you almost nothing in calories and adds seven grams of protein. Better dish on every measure." },
      { level: 2, label: "Drop a yolk", saves: 55, tasteCost: "Low",
        change: "Three eggs, two yolks.",
        why: "Whites are almost pure protein. Worth knowing, though whole eggs are fine for most people and the yolk holds the nutrients." },
      { level: 3, label: "Lose a roti", saves: 120, tasteCost: "Low",
        change: "One roti, more gravy.",
        why: "Standard move. The eggs are the meal." },
    ],
  },
  {
    id: "fish-curry", name: "Fish curry with rice", category: "south",
    veg: false, verified: false, image: null, role: "solution",
    portion: "1 katori fish curry + 1 katori rice",
    headline: "Fish is the most efficient protein on any Indian menu. The coconut is where it gets expensive.",
    components: [
      { name: "Fish", qty: "~150 g", grams: 150, kcal: 180, carb: 0, protein: 30, fat: 6, fibre: 0,
        verdict: "good", note: "Thirty grams of protein for 180 calories. Nothing in this library beats that ratio." },
      { name: "Coconut in the gravy", qty: "—", grams: 50, kcal: 165, carb: 6, protein: 2, fat: 15, fibre: 3,
        verdict: "driver", note: "Coconut is roughly a third fat by weight. It is also what makes the dish taste like itself." },
      { name: "Tamarind, curry leaves, spice", qty: "—", grams: 40, kcal: 30, carb: 5, protein: 1, fat: 0, fibre: 1,
        verdict: "good", note: "Free flavour." },
      { name: "Rice", qty: "1 katori", grams: 100, kcal: 130, carb: 28, protein: 2, fat: 0, fibre: 1,
        verdict: "neutral", note: "Modest portion, which is unusual for this library." },
    ],
    tiers: [
      { level: 1, label: "Order it as it comes", saves: 0, tasteCost: "None",
        change: "Around 505 calories with 35 grams of protein. This is a good meal.",
        why: "Coconut gravy is fatty, but the dish as a whole is one of the best-balanced things in Indian cooking." },
      { level: 2, label: "Thin the coconut", saves: 80, tasteCost: "Moderate",
        change: "Second-press coconut milk rather than first, or a thinner gravy.",
        why: "Common in home cooking already. You lose some richness, not the flavour." },
      { level: 3, label: "Grill it instead", saves: 165, tasteCost: "High — a different dish",
        change: "Tawa or tandoori fish with lemon.",
        why: "All the protein, none of the coconut. Excellent, but it is not fish curry." },
    ],
  },
  {
    id: "keema", name: "Keema", category: "north",
    veg: false, verified: false, image: null, role: "solution",
    portion: "1 katori keema + 2 roti",
    headline: "Mince brings its own fat, and then the recipe adds more on top.",
    components: [
      { name: "Mince", qty: "~150 g", grams: 150, kcal: 300, carb: 0, protein: 30, fat: 20, fibre: 0,
        verdict: "good", note: "Thirty grams of protein, but standard mince is around 20% fat before anything is added." },
      { name: "Oil", qty: "~1.5 tbsp", grams: 20, kcal: 175, carb: 0, protein: 0, fat: 20, fibre: 0,
        verdict: "driver", note: "Largely unnecessary. Mince releases enough of its own fat to cook in." },
      { name: "Peas, onion, tomato", qty: "—", grams: 100, kcal: 70, carb: 11, protein: 3, fat: 1, fibre: 4,
        verdict: "good", note: "Peas add protein and fibre. Worth doubling." },
      { name: "Roti", qty: "2 pieces", grams: 80, kcal: 240, carb: 46, protein: 8, fat: 2, fibre: 6,
        verdict: "neutral", note: "Standard." },
    ],
    tiers: [
      { level: 1, label: "Cook it in its own fat", saves: 175, tasteCost: "None",
        change: "Brown the mince first with no oil at all, then build the masala in the rendered fat.",
        why: "The single largest saving available in this dish, and it improves the texture. Most cooks add oil out of habit." },
      { level: 2, label: "Lean mince, more peas", saves: 90, tasteCost: "Low",
        change: "Lean chicken or mutton mince, and double the peas.",
        why: "Keeps the protein, drops the fat, adds fibre." },
      { level: 3, label: "Keema with salad, not roti", saves: 240, tasteCost: "Moderate",
        change: "A large portion of keema with onion and cucumber salad.",
        why: "Low-carb compatible, and keema is rich enough to carry a meal without bread." },
    ],
  },
  {
    id: "egg-bhurji", name: "Egg bhurji", category: "breakfast",
    veg: false, verified: false, image: null, role: "solution",
    portion: "3 eggs, scrambled Indian style",
    headline: "Twenty grams of protein in five minutes. The best breakfast on this site, and nobody treats it as one.",
    components: [
      { name: "Eggs", qty: "3 whole", grams: 165, kcal: 235, carb: 2, protein: 19, fat: 16, fibre: 0,
        verdict: "good", note: "Nineteen grams of protein at breakfast is the difference between eating lunch and eating a samosa at eleven." },
      { name: "Oil or butter", qty: "1 tbsp", grams: 14, kcal: 125, carb: 0, protein: 0, fat: 14, fibre: 0,
        verdict: "driver", note: "Two teaspoons is plenty in a non-stick pan." },
      { name: "Onion, tomato, chilli, coriander", qty: "—", grams: 80, kcal: 40, carb: 7, protein: 1, fat: 0, fibre: 2,
        verdict: "good", note: "What makes it bhurji rather than scrambled eggs." },
    ],
    tiers: [
      { level: 1, label: "Less fat, same eggs", saves: 60, tasteCost: "None",
        change: "Two teaspoons of oil in a non-stick pan.",
        why: "Around 340 calories with 20 grams of protein. Compare that to poha at 360 with six." },
      { level: 2, label: "Add more vegetables", saves: 0, tasteCost: "None",
        change: "Double the onion and tomato, add spinach or capsicum.",
        why: "More volume and fibre for almost no calories. Makes three eggs feel like a full plate." },
      { level: 3, label: "Skip the roti", saves: 240, tasteCost: "Low",
        change: "Bhurji on its own, or with one roti rather than two.",
        why: "The eggs are already a meal. The bread is habit." },
    ],
  },
  {
    id: "chilli-chicken", name: "Chilli chicken", category: "street",
    veg: false, verified: false, image: null, role: "problem",
    portion: "One restaurant plate",
    headline: "The protein is real. So is the batter, the fryer, and the sugar in the sauce.",
    components: [
      { name: "Chicken", qty: "~150 g", grams: 150, kcal: 250, carb: 0, protein: 37, fat: 11, fibre: 0,
        verdict: "good", note: "Genuinely good protein, buried under three layers of processing." },
      { name: "Cornflour batter and frying oil", qty: "—", grams: 55, kcal: 300, carb: 20, protein: 2, fat: 25, fibre: 0,
        verdict: "driver", note: "Battered then deep fried. This is nearly half the plate and it exists purely for texture." },
      { name: "Sauce", qty: "—", grams: 60, kcal: 100, carb: 20, protein: 1, fat: 2, fibre: 1,
        verdict: "driver", note: "Sugar, soy, cornflour thickener. More sugar than most people would guess." },
    ],
    tiers: [
      { level: 1, label: "Dry, not gravy", saves: 60, tasteCost: "Low",
        change: "Order the dry version rather than the gravy one.",
        why: "Less sauce means less sugar and less cornflour. The chicken is the same." },
      { level: 2, label: "Order chicken tikka instead", saves: 400, tasteCost: "High — a different dish",
        change: "Tandoori or tikka for the same protein.",
        why: "Same 37 grams of protein for around 250 calories rather than 650. This is the honest comparison." },
      { level: 3, label: "Home version", saves: 350, tasteCost: "Moderate",
        change: "Pan-seared chicken, no batter, sauce made with less sugar.",
        why: "Keeps the flavour profile, loses the fryer. Not the same texture, and that is the whole trade." },
    ],
  },
  {
    id: "paneer-tikka", name: "Paneer tikka", category: "north",
    veg: true, verified: false, image: null, role: "solution",
    portion: "~150 g, 6 pieces",
    headline: "The paneer dish worth ordering. No cream, no cashew, all of the protein.",
    components: [
      { name: "Paneer", qty: "6 pieces", grams: 150, kcal: 435, carb: 4, protein: 27, fat: 34, fibre: 0,
        verdict: "good", note: "Twenty-seven grams of protein. Also thirty-four of fat — paneer is not a lean food, but it is a genuinely high-protein vegetarian one." },
      { name: "Yoghurt marinade and capsicum", qty: "—", grams: 90, kcal: 60, carb: 6, protein: 3, fat: 2, fibre: 2,
        verdict: "good", note: "Curd, spice, and the peppers and onion on the skewer. Adds protein and fibre for very little." },
    ],
    tiers: [
      { level: 1, label: "Order it instead of the gravy version", saves: 300, tasteCost: "None if you like tikka",
        change: "Paneer tikka rather than paneer butter masala.",
        why: "Same ingredient, same protein, none of the cream. Roughly 300 fewer calories for the same satisfaction." },
      { level: 2, label: "Low-fat paneer", saves: 130, tasteCost: "Low",
        change: "Made with low-fat paneer at home.",
        why: "Keeps the protein, cuts a third of the fat. In a spiced marinade the difference is barely noticeable." },
      { level: 3, label: "More vegetables on the skewer", saves: 100, tasteCost: "None",
        change: "Alternate paneer with capsicum, onion and mushroom.",
        why: "Same plate, fewer calories, more fibre, and it looks better." },
    ],
  },
  {
    id: "sprouts-usal", name: "Sprouts usal", category: "baseline",
    veg: true, verified: false, image: null, role: "solution",
    portion: "1 katori",
    headline: "Thirteen grams of protein and nine of fibre for 270 calories. Almost nothing else here comes close.",
    components: [
      { name: "Sprouted moong or matki", qty: "1 katori", grams: 150, kcal: 150, carb: 22, protein: 12, fat: 1, fibre: 8,
        verdict: "good", note: "Sprouting raises the protein availability and the fibre. This is the most efficient vegetarian food in the library." },
      { name: "Oil and tempering", qty: "1 tbsp", grams: 12, kcal: 105, carb: 0, protein: 0, fat: 12, fibre: 0,
        verdict: "neutral", note: "Needed for the tadka. Two teaspoons is enough." },
      { name: "Onion, tomato, coriander, lemon", qty: "—", grams: 60, kcal: 25, carb: 5, protein: 1, fat: 0, fibre: 1,
        verdict: "good", note: "Free." },
    ],
    tiers: [
      { level: 1, label: "Leave it alone", saves: 0, tasteCost: "None",
        change: "Nothing. This is one of the best things you can eat.",
        why: "Twelve grams of plant protein and eight of fibre for 280 calories. If you want one habit from this entire site, it is eating this twice a week." },
      { level: 2, label: "Make it the meal", saves: 0, tasteCost: "None",
        change: "Two katori with one roti, rather than a side dish.",
        why: "Usal is usually treated as an accompaniment. It is substantial enough to be lunch." },
      { level: 3, label: "Add curd", saves: 0, tasteCost: "None",
        change: "A katori of curd alongside.",
        why: "Takes the protein past twenty grams and makes it a complete amino acid profile." },
    ],
  },
  {
    id: "dal-tadka", name: "Dal tadka", category: "baseline",
    veg: true, verified: false, image: null, role: "solution",
    portion: "1 katori dal + 2 roti",
    headline: "The dal you should actually be eating. Dal makhani's calories come from the cream, not the lentils.",
    components: [
      { name: "Toor or moong dal", qty: "1 katori", grams: 150, kcal: 170, carb: 24, protein: 10, fat: 2, fibre: 6,
        verdict: "good", note: "Ten grams of protein, six of fibre. The same legumes as dal makhani, prepared honestly." },
      { name: "Tadka ghee", qty: "1 tbsp", grams: 12, kcal: 105, carb: 0, protein: 0, fat: 12, fibre: 0,
        verdict: "neutral", note: "The tempering is the dish. Cumin, garlic and chilli bloomed in ghee is not something to economise on." },
      { name: "Roti", qty: "2 pieces", grams: 80, kcal: 240, carb: 46, protein: 8, fat: 2, fibre: 6,
        verdict: "neutral", note: "Standard, and dal with roti is a complete protein." },
    ],
    tiers: [
      { level: 1, label: "Order this instead of dal makhani", saves: 310, tasteCost: "Real — it is a different dal",
        change: "Dal tadka or dal fry rather than makhani.",
        why: "Same lentils, 310 fewer calories. Worth knowing that the difference between the two dishes is almost entirely cream and butter." },
      { level: 2, label: "Add curd, drop a roti", saves: 120, tasteCost: "None",
        change: "One roti, a katori of curd alongside.",
        why: "Better protein ratio and it holds you longer." },
      { level: 3, label: "Mix the dals", saves: 0, tasteCost: "None",
        change: "Panchmel — five lentils together.",
        why: "Broader amino acid profile and more fibre for the same calories. Traditional in Rajasthan and better than any single dal." },
    ],
  },
];
