/**
 * Dish library, part two — Healthyram
 * © 2026 Aseem Mohan. All rights reserved.
 *
 * INSTALL AT: lib/dishes-more.js
 *
 * ─────────────────────────────────────────────────────────────
 * DATA STATUS: ESTIMATES. NOT VERIFIED AGAINST IFCT 2017.
 * Same caveat as dishes.js. Absorbed frying oil and applied ghee
 * are the least certain figures and are always estimates.
 * ─────────────────────────────────────────────────────────────
 */

export const MORE_DISHES = [
  /* ---------------- BREAKFAST ---------------- */
  {
    id: "upma", name: "Upma", category: "breakfast", veg: true, verified: false, image: null,
    portion: "One katori, ~150 g cooked",
    headline: "Sooji is refined wheat. Upma is closer to white bread than to porridge.",
    components: [
      { name: "Semolina", qty: "~1 katori dry", grams: 50, kcal: 180, carb: 37, protein: 5, fat: 1, fibre: 2,
        verdict: "driver", note: "Sooji is milled wheat with the bran and germ removed. The health reputation is inherited from the grain, not the product." },
      { name: "Oil and ghee", qty: "1.5 tbsp", grams: 20, kcal: 175, carb: 0, protein: 0, fat: 20, fibre: 0,
        verdict: "driver", note: "Upma needs fat to keep the grains separate. Most kitchens use considerably more than the recipe says." },
      { name: "Vegetables, cashew, curry leaves", qty: "—", grams: 40, kcal: 65, carb: 6, protein: 2, fat: 4, fibre: 2,
        verdict: "good", note: "The only fibre and most of the protein. Worth doubling." },
    ],
    tiers: [
      { level: 1, label: "Halve the fat, double the vegetables", saves: 90, tasteCost: "Low",
        change: "Two teaspoons of oil rather than a tablespoon and a half. Twice the vegetables.",
        why: "Same plate, better texture than people expect, and the fibre changes how long it holds you." },
      { level: 2, label: "Add protein", saves: 0, tasteCost: "None",
        change: "Two eggs, a katori of curd, or sprouts alongside.",
        why: "Upma's problem is not calories, it is that a bowl of refined carbohydrate at 8 am guarantees you are hungry at 11." },
      { level: 3, label: "Change the grain", saves: 120, tasteCost: "Moderate",
        change: "Oats upma, quinoa upma, or broken wheat.",
        why: "Same method, same tempering, three times the fibre. This is one of the easier swaps to live with." },
    ],
  },
  {
    id: "paratha", name: "Stuffed paratha", category: "breakfast", veg: true, verified: false, image: null,
    portion: "2 aloo paratha with butter",
    headline: "A whole meal's calories before anyone puts butter on top. Then somebody does.",
    components: [
      { name: "Wheat dough", qty: "2 parathas", grams: 100, kcal: 340, carb: 68, protein: 11, fat: 3, fibre: 8,
        verdict: "neutral", note: "Whole wheat, reasonable fibre. Fine in itself, but this is two rotis' worth of flour per paratha." },
      { name: "Potato filling", qty: "—", grams: 120, kcal: 120, carb: 22, protein: 3, fat: 1, fibre: 3,
        verdict: "neutral", note: "Cheap calories, but not where the damage is." },
      { name: "Ghee, cooking and applied", qty: "~2 tbsp", grams: 27, kcal: 240, carb: 0, protein: 0, fat: 27, fibre: 0,
        verdict: "driver", note: "Split roughly evenly between the tawa and the spoonful added at the table. The second half is entirely optional and nobody counts it." },
    ],
    tiers: [
      { level: 1, label: "Skip the butter at the table", saves: 120, tasteCost: "Low",
        change: "Cook it in ghee if you like. Do not add more afterwards. Curd on the side instead.",
        why: "Half the fat in this dish is applied after cooking, when the paratha is already made. That half is free to remove." },
      { level: 2, label: "One paratha, more curd", saves: 230, tasteCost: "None",
        change: "One paratha with a full katori of curd.",
        why: "The curd adds protein and volume. One paratha plus curd is more filling than two parathas alone, which surprises people." },
      { level: 3, label: "Change the filling", saves: 100, tasteCost: "Moderate",
        change: "Paneer, methi or mixed dal instead of potato.",
        why: "Turns a carbohydrate-on-carbohydrate dish into something with real protein in it." },
    ],
  },
  {
    id: "bread-pakora", name: "Bread pakora", category: "breakfast", veg: true, verified: false, image: null,
    portion: "One piece",
    headline: "Bread is a sponge. Deep-fried bread is a sponge that has been held under oil.",
    components: [
      { name: "White bread", qty: "2 slices", grams: 55, kcal: 145, carb: 27, protein: 5, fat: 1, fibre: 1,
        verdict: "neutral", note: "Refined, airy, and structurally perfect for absorbing fat." },
      { name: "Potato filling and besan coating", qty: "—", grams: 60, kcal: 110, carb: 18, protein: 4, fat: 2, fibre: 2,
        verdict: "neutral", note: "The besan is the only redeeming ingredient here." },
      { name: "Absorbed frying oil", qty: "—", grams: 20, kcal: 180, carb: 0, protein: 0, fat: 20, fibre: 0,
        verdict: "driver", note: "Bread's air pockets fill with oil during frying. This is why bread pakora is heavier than a samosa of the same size." },
    ],
    tiers: [
      { level: 1, label: "One, not two, and not with chai every day", saves: 435, tasteCost: "None",
        change: "Treat it as an occasional thing rather than a breakfast.",
        why: "There is no useful engineering here. Frequency is the only lever." },
      { level: 2, label: "Air-fry it", saves: 160, tasteCost: "High — the crust is different",
        change: "Air-fried at 190°C after a light brush of oil.",
        why: "Removes most of the absorbed oil, which is the whole problem. The texture is genuinely not the same." },
      { level: 3, label: "Change the snack", saves: 300, tasteCost: "High",
        change: "Besan chilla, or a masala omelette on one slice of toast.",
        why: "Similar effort, similar savoury satisfaction, four times the protein." },
    ],
  },

  /* ---------------- NORTH ---------------- */
  {
    id: "rajma-chawal", name: "Rajma chawal", category: "north", veg: true, verified: false, image: null,
    portion: "1 katori rajma + 2 katori rice",
    headline: "Rajma is one of the best things you can eat. It usually arrives buried under twice the rice it needs.",
    components: [
      { name: "Kidney beans", qty: "1 katori", grams: 150, kcal: 160, carb: 24, protein: 9, fat: 1, fibre: 9,
        verdict: "good", note: "Nine grams of fibre and nine of protein in one bowl. Very few Indian dishes do better." },
      { name: "Oil in the gravy", qty: "~1.5 tbsp", grams: 20, kcal: 175, carb: 0, protein: 0, fat: 20, fibre: 0,
        verdict: "driver", note: "Restaurant rajma is a fat-heavy gravy. Home rajma often is too." },
      { name: "Rice", qty: "2 katori cooked", grams: 200, kcal: 260, carb: 56, protein: 5, fat: 1, fibre: 1,
        verdict: "driver", note: "The default portion is roughly double what the beans need to be a complete meal." },
    ],
    tiers: [
      { level: 1, label: "Flip the ratio", saves: 130, tasteCost: "None",
        change: "One katori of rice, two of rajma.",
        why: "More protein, more fibre, fewer calories, and it is more filling. The single best change on this page." },
      { level: 2, label: "Cut the gravy oil", saves: 120, tasteCost: "Low",
        change: "One tablespoon of oil at home, or skim the top layer when eating out.",
        why: "Rajma carries its own flavour from long cooking. The oil is a shortcut, not a requirement." },
      { level: 3, label: "Change the grain", saves: 60, tasteCost: "Moderate",
        change: "Brown rice, or half rice and half cauliflower rice.",
        why: "Slower digesting, more fibre. Rajma is robust enough to carry a different base." },
    ],
  },
  {
    id: "paneer-butter", name: "Paneer butter masala", category: "north", veg: true, verified: false, image: null,
    portion: "1 katori + 2 roti",
    headline: "Paneer is protein and fat in roughly equal measure. Then the gravy doubles the fat again.",
    components: [
      { name: "Paneer", qty: "~100 g", grams: 100, kcal: 290, carb: 3, protein: 18, fat: 23, fibre: 0,
        verdict: "neutral", note: "Genuine protein, but full-fat paneer is around a quarter fat by weight. It is not the lean vegetarian option people assume." },
      { name: "Cream, butter and cashew", qty: "in the gravy", grams: 55, kcal: 250, carb: 8, protein: 3, fat: 23, fibre: 1,
        verdict: "driver", note: "The same gravy as butter chicken, on an ingredient that was already fatty." },
      { name: "Roti", qty: "2 pieces", grams: 80, kcal: 240, carb: 46, protein: 8, fat: 2, fibre: 6,
        verdict: "neutral", note: "Whole wheat and unbuttered. The sensible part of the plate." },
    ],
    tiers: [
      { level: 1, label: "Keep the paneer, lose the cream", saves: 180, tasteCost: "Low",
        change: "Ask for a tomato-based gravy rather than makhani, where the kitchen offers it.",
        why: "You came for the paneer. The cream is doing less flavour work than the spice is." },
      { level: 2, label: "Switch the paneer", saves: 100, tasteCost: "Low",
        change: "Low-fat or malai-free paneer at home.",
        why: "Keeps the protein, removes a third of the fat, and in a spiced gravy the difference is barely detectable." },
      { level: 3, label: "Change the preparation", saves: 320, tasteCost: "Moderate",
        change: "Paneer tikka or bhurji with two roti.",
        why: "Same ingredient, same protein, no cream at all. Bhurji in particular is badly underrated." },
    ],
  },
  {
    id: "kadhi-chawal", name: "Kadhi chawal", category: "north", veg: true, verified: false, image: null,
    portion: "1 katori kadhi with 3 pakora + 1.5 katori rice",
    headline: "Kadhi without the pakoras is one of the lightest things in North Indian cooking.",
    components: [
      { name: "Kadhi base, curd and besan", qty: "1 katori", grams: 150, kcal: 120, carb: 10, protein: 6, fat: 6, fibre: 1,
        verdict: "good", note: "Fermented curd, gram flour, and a lot of water. Protein without much else." },
      { name: "Pakora in the kadhi", qty: "3 pieces", grams: 60, kcal: 210, carb: 15, protein: 4, fat: 14, fibre: 2,
        verdict: "driver", note: "Deep-fried, then soaked in the kadhi so they hold even more. Almost twice the calories of the kadhi they sit in." },
      { name: "Rice", qty: "1.5 katori", grams: 150, kcal: 195, carb: 42, protein: 4, fat: 0, fibre: 1,
        verdict: "neutral", note: "Standard portion issue." },
      { name: "Tempering ghee", qty: "1 tbsp", grams: 10, kcal: 90, carb: 0, protein: 0, fat: 10, fibre: 0,
        verdict: "neutral", note: "The tadka is the flavour. Leave it." },
    ],
    tiers: [
      { level: 1, label: "Kadhi without pakoras", saves: 210, tasteCost: "Real, if pakoras are the point for you",
        change: "Plain kadhi with rice.",
        why: "Removes a third of the meal and the entire fried component. Plain kadhi chawal is a genuinely light lunch." },
      { level: 2, label: "Fewer pakoras, less rice", saves: 210, tasteCost: "Low",
        change: "One pakora instead of three, one katori of rice instead of one and a half.",
        why: "Keeps the thing you like about it while halving both problems." },
      { level: 3, label: "Bake the pakoras", saves: 130, tasteCost: "Moderate",
        change: "Air-fried besan dumplings dropped into the kadhi.",
        why: "They soften in the kadhi anyway, so the texture loss matters less here than it would elsewhere." },
    ],
  },
  {
    id: "chana-masala", name: "Chana masala with roti", category: "north", veg: true, verified: false, image: null,
    portion: "1 katori chana + 2 roti",
    headline: "This is chole bhature done properly. Same chickpeas, roughly half the calories.",
    components: [
      { name: "Chickpeas", qty: "1 katori", grams: 150, kcal: 130, carb: 22, protein: 8, fat: 2, fibre: 7,
        verdict: "good", note: "Fibre, protein, low glycaemic load. Unchanged from the chole bhature page — because the chickpeas were never the problem." },
      { name: "Oil in the gravy", qty: "1 tbsp", grams: 14, kcal: 125, carb: 0, protein: 0, fat: 14, fibre: 0,
        verdict: "neutral", note: "Home portions are usually reasonable. Restaurant versions are not." },
      { name: "Roti", qty: "2 pieces", grams: 80, kcal: 240, carb: 46, protein: 8, fat: 2, fibre: 6,
        verdict: "neutral", note: "Whole wheat, no added fat. This is what bhatura should have been." },
    ],
    tiers: [
      { level: 1, label: "Add curd", saves: 0, tasteCost: "None",
        change: "A katori of plain curd alongside.",
        why: "This meal is already well built. The only thing it is short of is protein, and curd fixes that for 60 calories." },
      { level: 2, label: "Watch the oil", saves: 60, tasteCost: "None",
        change: "Two teaspoons rather than a tablespoon.",
        why: "Chana masala carries strong spice. The oil contributes less flavour here than in a cream-based gravy." },
      { level: 3, label: "Drop a roti", saves: 120, tasteCost: "Low",
        change: "One roti, two katori chana.",
        why: "More fibre, more protein, fewer calories, and you will not finish hungry." },
    ],
  },

  /* ---------------- SOUTH ---------------- */
  {
    id: "dosa", name: "Masala dosa", category: "south", veg: true, verified: false, image: null,
    portion: "1 masala dosa with sambar and chutney",
    headline: "The dosa is fine. It is what the tawa and the chutney add that you are not counting.",
    components: [
      { name: "Fermented batter", qty: "1 dosa", grams: 90, kcal: 170, carb: 33, protein: 4, fat: 1, fibre: 1,
        verdict: "neutral", note: "Rice and urad dal, fermented. Thin, light, and better than most breakfast breads." },
      { name: "Oil and ghee on the tawa", qty: "~2 tsp", grams: 10, kcal: 90, carb: 0, protein: 0, fat: 10, fibre: 0,
        verdict: "driver", note: "Restaurant dosas are cooked in far more fat than home versions. A crisp dosa is a well-oiled dosa." },
      { name: "Potato masala", qty: "—", grams: 100, kcal: 130, carb: 18, protein: 3, fat: 5, fibre: 3,
        verdict: "neutral", note: "Potato and tempering. Not the problem, but not doing much for you either." },
      { name: "Coconut chutney and sambar", qty: "—", grams: 180, kcal: 200, carb: 15, protein: 6, fat: 12, fibre: 6,
        verdict: "neutral", note: "The sambar earns its place. The coconut chutney is where the fat quietly arrives, and refills are free." },
    ],
    tiers: [
      { level: 1, label: "Plain dosa, extra sambar", saves: 130, tasteCost: "Low",
        change: "Plain dosa instead of masala, with a second bowl of sambar.",
        why: "Drops the potato, adds protein and fibre, and the sambar is the best thing on the tray." },
      { level: 2, label: "One serving of chutney", saves: 90, tasteCost: "None",
        change: "One spoon of coconut chutney, no refills.",
        why: "Coconut is fat-dense and free refills are how a light meal stops being light." },
      { level: 3, label: "Change the batter", saves: 60, tasteCost: "Moderate",
        change: "Ragi, oats or moong dal dosa.",
        why: "More fibre and protein, and moong dal dosa in particular holds up well." },
    ],
  },
  {
    id: "sambar-rice", name: "Sambar rice", category: "south", veg: true, verified: false, image: null,
    portion: "1.5 katori rice + 1 katori sambar",
    headline: "The sambar is doing all the nutritional work and getting a third of the plate.",
    components: [
      { name: "Rice", qty: "1.5 katori cooked", grams: 200, kcal: 260, carb: 56, protein: 5, fat: 1, fibre: 1,
        verdict: "driver", note: "Two thirds of the meal by calories, and the part contributing least." },
      { name: "Sambar", qty: "1 katori", grams: 150, kcal: 110, carb: 12, protein: 5, fat: 4, fibre: 4,
        verdict: "good", note: "Toor dal and vegetables. Protein, fibre and flavour in one bowl." },
      { name: "Ghee", qty: "1 tsp", grams: 5, kcal: 45, carb: 0, protein: 0, fat: 5, fibre: 0,
        verdict: "neutral", note: "A teaspoon of ghee on sambar rice is one of the better 45 calories you will spend." },
    ],
    tiers: [
      { level: 1, label: "Flip the ratio", saves: 90, tasteCost: "None",
        change: "One katori of rice, two of sambar.",
        why: "Better on every measure and it costs you nothing in taste. Ask for extra sambar — most places give it free." },
      { level: 2, label: "Add a protein", saves: 0, tasteCost: "None",
        change: "Curd, a boiled egg, or a side of paruppu.",
        why: "Sambar rice is comfortable but light on protein for a main meal." },
      { level: 3, label: "Change the grain", saves: 60, tasteCost: "Moderate",
        change: "Brown rice or millet.",
        why: "The sambar carries enough flavour to make the grain almost incidental." },
    ],
  },
  {
    id: "curd-rice", name: "Curd rice", category: "south", veg: true, verified: false, image: null,
    portion: "One plate, ~250 g",
    headline: "One of the few Indian dishes that is genuinely light without trying to be.",
    components: [
      { name: "Rice", qty: "1.5 katori cooked", grams: 150, kcal: 195, carb: 42, protein: 4, fat: 0, fibre: 1,
        verdict: "driver", note: "The bulk of the dish, though the portion is usually modest." },
      { name: "Curd", qty: "~1 katori", grams: 100, kcal: 60, carb: 3, protein: 3, fat: 3, fibre: 0,
        verdict: "good", note: "Protein, and live cultures. The thing that makes this dish work." },
      { name: "Tempering, curry leaves, ginger", qty: "—", grams: 12, kcal: 60, carb: 1, protein: 0, fat: 6, fibre: 0,
        verdict: "neutral", note: "Small and worth it." },
    ],
    tiers: [
      { level: 1, label: "Leave it alone", saves: 0, tasteCost: "None",
        change: "Nothing. Around 315 calories with protein and probiotics in it.",
        why: "Not every dish needs fixing. This one is fine as it is, and saying so matters as much as flagging the ones that are not." },
      { level: 2, label: "More curd, less rice", saves: 65, tasteCost: "None",
        change: "One katori of rice, one and a half of curd.",
        why: "Better protein ratio, and arguably a better dish." },
      { level: 3, label: "Add vegetables", saves: 0, tasteCost: "None",
        change: "Grated carrot, cucumber, pomegranate.",
        why: "Adds fibre and texture for almost no calories. Standard in many households already." },
    ],
  },
  {
    id: "uttapam", name: "Uttapam", category: "south", veg: true, verified: false, image: null,
    portion: "1 uttapam with sambar and chutney",
    headline: "Thicker than a dosa, which means more batter and more oil to cook it through.",
    components: [
      { name: "Fermented batter", qty: "1 uttapam", grams: 130, kcal: 250, carb: 48, protein: 6, fat: 1, fibre: 2,
        verdict: "driver", note: "Roughly one and a half times a dosa's batter, because thickness is the point." },
      { name: "Oil", qty: "~2 tsp", grams: 10, kcal: 90, carb: 0, protein: 0, fat: 10, fibre: 0,
        verdict: "neutral", note: "Less per gram than a dosa, since there is less surface area to crisp." },
      { name: "Onion, tomato, chilli topping", qty: "—", grams: 60, kcal: 30, carb: 5, protein: 1, fat: 0, fibre: 2,
        verdict: "good", note: "Nearly free, and the reason to order this over a plain dosa." },
      { name: "Chutney and sambar", qty: "—", grams: 180, kcal: 200, carb: 15, protein: 6, fat: 12, fibre: 6,
        verdict: "neutral", note: "Same as with dosa. The coconut chutney is the variable." },
    ],
    tiers: [
      { level: 1, label: "Load the topping, watch the chutney", saves: 90, tasteCost: "None",
        change: "Ask for extra vegetables on top. One serving of chutney.",
        why: "The topping is the cheapest thing on the plate and the only source of fibre." },
      { level: 2, label: "Smaller, with more sambar", saves: 120, tasteCost: "Low",
        change: "A smaller uttapam and a second bowl of sambar.",
        why: "Shifts the meal from batter towards dal without changing what you ordered." },
      { level: 3, label: "Change the batter", saves: 70, tasteCost: "Moderate",
        change: "Oats or moong dal uttapam.",
        why: "Uttapam takes a substituted batter better than dosa does, because it does not need to crisp." },
    ],
  },

  /* ---------------- STREET ---------------- */
  {
    id: "pav-bhaji", name: "Pav bhaji", category: "street", veg: true, verified: false, image: null,
    portion: "2 pav + 1 katori bhaji",
    headline: "The bhaji is mashed vegetables. Then someone adds three tablespoons of butter.",
    components: [
      { name: "Mashed vegetables", qty: "1 katori", grams: 200, kcal: 100, carb: 18, protein: 4, fat: 1, fibre: 6,
        verdict: "good", note: "Potato, peas, cauliflower, capsicum. Six grams of fibre. On its own this is a genuinely good bowl of food." },
      { name: "Butter, in the bhaji and on the pav", qty: "~3 tbsp", grams: 40, kcal: 290, carb: 0, protein: 0, fat: 33, fibre: 0,
        verdict: "driver", note: "The visible slab on top is only part of it. More goes in during cooking, and the pav is fried in it." },
      { name: "Pav", qty: "2 pieces", grams: 100, kcal: 270, carb: 52, protein: 8, fat: 3, fibre: 2,
        verdict: "driver", note: "Refined white bread, and the butter it is toasted in is counted above." },
    ],
    tiers: [
      { level: 1, label: "Ask them to hold the butter slab", saves: 150, tasteCost: "Low",
        change: "No butter on top, and one pav rather than two.",
        why: "The bhaji is already cooked in butter. The slab added at serving is theatre, and it is 100 calories." },
      { level: 2, label: "Bhaji without the pav", saves: 270, tasteCost: "Real — the pav is half the dish",
        change: "A large bowl of bhaji on its own, or with one roti.",
        why: "You keep the vegetables and the flavour and lose the refined bread. Not everyone will accept this, and that is fair." },
      { level: 3, label: "Home version", saves: 400, tasteCost: "Moderate",
        change: "One tablespoon of butter total, whole wheat pav, extra vegetables.",
        why: "Pav bhaji survives this better than most dishes, because the spice mix does the heavy lifting." },
    ],
  },
  {
    id: "pani-puri", name: "Pani puri", category: "street", veg: true, verified: false, image: null,
    portion: "6 puri",
    headline: "One of the least damaging things on the cart. The water was never the problem.",
    components: [
      { name: "Fried puri shells", qty: "6 pieces", grams: 40, kcal: 180, carb: 20, protein: 3, fat: 10, fibre: 1,
        verdict: "driver", note: "Small, but deep fried. Almost all the calories in this dish are here." },
      { name: "Potato and chana filling", qty: "—", grams: 60, kcal: 70, carb: 13, protein: 3, fat: 0, fibre: 3,
        verdict: "good", note: "The chana adds a little protein and fibre. Ask for more of it." },
      { name: "Pani", qty: "—", grams: 120, kcal: 15, carb: 3, protein: 0, fat: 0, fibre: 0,
        verdict: "good", note: "Spiced water. Essentially free, and the entire flavour of the dish." },
    ],
    tiers: [
      { level: 1, label: "Stop at six", saves: 265, tasteCost: "Willpower, not taste",
        change: "Six is a snack. The second plate is where this stops being harmless.",
        why: "Six puri is around 265 calories. Nobody eats six. The portion is the only real variable." },
      { level: 2, label: "More chana, less potato", saves: 20, tasteCost: "None",
        change: "Ask for the chana filling rather than potato.",
        why: "Marginal on calories, meaningfully better on protein and fibre." },
      { level: 3, label: "Skip the sweet chutney", saves: 60, tasteCost: "Low",
        change: "Tangy pani only, no meetha chutney.",
        why: "The sweet chutney is mostly jaggery and dates. The spiced water is where the flavour lives anyway." },
    ],
  },
  {
    id: "bhel-sev-puri", name: "Bhel puri", category: "street", veg: true, verified: false, image: null,
    portion: "One standard plate",
    headline: "Puffed rice is nearly weightless. The sev and the sweet chutney are not.",
    components: [
      { name: "Puffed rice", qty: "~2 katori", grams: 30, kcal: 110, carb: 25, protein: 2, fat: 0, fibre: 1,
        verdict: "neutral", note: "Almost air. This is the part everyone assumes is the problem and it is not." },
      { name: "Sev and fried papdi", qty: "—", grams: 25, kcal: 135, carb: 12, protein: 3, fat: 9, fibre: 1,
        verdict: "driver", note: "Deep-fried besan noodles. A small handful outweighs the entire bowl of puffed rice." },
      { name: "Sweet chutney", qty: "~2 tbsp", grams: 35, kcal: 75, carb: 18, protein: 0, fat: 0, fibre: 1,
        verdict: "driver", note: "Jaggery, dates, tamarind. Almost entirely sugar, and it is what makes bhel taste like bhel." },
      { name: "Onion, tomato, coriander, raw mango", qty: "—", grams: 60, kcal: 25, carb: 5, protein: 1, fat: 0, fibre: 2,
        verdict: "good", note: "Free flavour and fibre. Ask for extra." },
    ],
    tiers: [
      { level: 1, label: "Light on sev, light on sweet", saves: 130, tasteCost: "Low",
        change: "Ask for less sev and half the sweet chutney. Extra onion and raw mango.",
        why: "Both are made to order. Bhel is one of the few street foods where you can genuinely customise it as it is being mixed." },
      { level: 2, label: "Sukha bhel", saves: 75, tasteCost: "Moderate",
        change: "Dry bhel, chutney on the side.",
        why: "You control how much goes on rather than the vendor." },
      { level: 3, label: "Add protein", saves: 0, tasteCost: "None",
        change: "Ask for sprouts or boiled chana in the mix.",
        why: "Turns a snack that leaves you hungry into one that does not. Most carts have both." },
    ],
  },
  {
    id: "vada-pav", name: "Vada pav", category: "street", veg: true, verified: false, image: null,
    portion: "One vada pav",
    headline: "Refined bread wrapped around deep-fried potato. There is no protein in it anywhere.",
    components: [
      { name: "Pav", qty: "1 piece", grams: 60, kcal: 160, carb: 31, protein: 5, fat: 2, fibre: 1,
        verdict: "neutral", note: "White bread. The smaller half of the problem." },
      { name: "Potato and besan coating", qty: "1 vada", grams: 90, kcal: 165, carb: 26, protein: 5, fat: 4, fibre: 3,
        verdict: "neutral", note: "Potato is the filling; the besan batter is thin." },
      { name: "Absorbed frying oil", qty: "—", grams: 17, kcal: 155, carb: 0, protein: 0, fat: 17, fibre: 0,
        verdict: "driver", note: "Around a third of the calories, and entirely invisible." },
      { name: "Chutneys", qty: "—", grams: 25, kcal: 35, carb: 6, protein: 1, fat: 1, fibre: 1,
        verdict: "neutral", note: "Small. Not worth worrying about." },
    ],
    tiers: [
      { level: 1, label: "One, as a snack, not as lunch", saves: 515, tasteCost: "None",
        change: "One. Never two. Never as a meal.",
        why: "Around 515 calories with almost no protein means you are hungry again within ninety minutes. That is what makes it two." },
      { level: 2, label: "Vada without the pav", saves: 160, tasteCost: "Real",
        change: "The vada on its own with chutney.",
        why: "Common in Mumbai and nobody looks at you strangely for it." },
      { level: 3, label: "Change the snack", saves: 350, tasteCost: "High",
        change: "Roasted chana, boiled corn chaat, or an egg.",
        why: "Vada pav is not fixable. It is worth eating occasionally and worth not building a habit around." },
    ],
  },
  {
    id: "pakora", name: "Pakora", category: "street", veg: true, verified: false, image: null,
    portion: "~6 pieces, mixed vegetable",
    headline: "Besan is actually good for you. Then it spends four minutes in a fryer.",
    components: [
      { name: "Besan and vegetables", qty: "6 pieces", grams: 100, kcal: 150, carb: 20, protein: 7, fat: 3, fibre: 4,
        verdict: "good", note: "Gram flour has real protein and fibre. Onion, spinach and potato add more. Before frying, this is a decent food." },
      { name: "Absorbed frying oil", qty: "—", grams: 30, kcal: 270, carb: 0, protein: 0, fat: 30, fibre: 0,
        verdict: "driver", note: "Nearly two thirds of the calories. Pakora batter is loose and porous, which is exactly what maximises absorption." },
    ],
    tiers: [
      { level: 1, label: "A few, with the tea, on a plate", saves: 210, tasteCost: "None",
        change: "Serve a counted number on a plate instead of eating from the bowl.",
        why: "Pakora is eaten by the handful and the handfuls are not counted. Plating them is the entire intervention." },
      { level: 2, label: "Air-fry them", saves: 230, tasteCost: "High — the crunch is different",
        change: "Air-fried at 190°C with a spray of oil.",
        why: "Removes almost all the absorbed oil. The texture is drier and no amount of pretending changes that, but it is a legitimately different snack." },
      { level: 3, label: "Change the form", saves: 200, tasteCost: "Moderate",
        change: "Besan chilla, or steamed dhokla.",
        why: "Same gram flour, same protein, no fryer. Dhokla in particular is one of the best snacks in Indian cooking and nobody treats it as one." },
    ],
  },
  {
    id: "momos", name: "Momos", category: "street", veg: false, verified: false, image: null,
    portion: "8 steamed chicken momos with chutney",
    headline: "Steamed, with actual protein inside. Then people order them fried.",
    components: [
      { name: "Wrapper", qty: "8 pieces", grams: 120, kcal: 240, carb: 50, protein: 7, fat: 1, fibre: 2,
        verdict: "driver", note: "Refined flour, but steamed rather than fried. The largest component, and still not a disaster." },
      { name: "Chicken filling", qty: "—", grams: 120, kcal: 160, carb: 2, protein: 20, fat: 8, fibre: 1,
        verdict: "good", note: "Twenty grams of protein. Almost nothing else on this street cart comes close." },
      { name: "Chutney", qty: "—", grams: 40, kcal: 60, carb: 8, protein: 1, fat: 3, fibre: 1,
        verdict: "neutral", note: "Modest, unless it is a mayonnaise-based one, in which case double it." },
    ],
    tiers: [
      { level: 1, label: "Steamed, always", saves: 240, tasteCost: "None if you never had them fried",
        change: "Steamed rather than fried or pan-fried.",
        why: "Frying adds roughly 240 calories to the same eight momos. This is the single decision that matters here." },
      { level: 2, label: "Chicken over veg", saves: 0, tasteCost: "None",
        change: "Chicken filling rather than cabbage.",
        why: "Vegetable momos are wrapper with a little cabbage in them — nearly all refined flour. Chicken makes it a meal." },
      { level: 3, label: "Watch the mayo chutney", saves: 120, tasteCost: "Low",
        change: "Red chilli chutney, not the creamy one.",
        why: "Mayonnaise-based dips can add more calories than two extra momos." },
    ],
  },

  /* ---------------- SWEETS ---------------- */
  {
    id: "jalebi", name: "Jalebi", category: "sweet", veg: true, verified: false, image: null,
    portion: "2 pieces, ~60 g",
    headline: "Roughly half the weight of a jalebi is sugar syrup. That is the design, not a flaw.",
    components: [
      { name: "Fried batter", qty: "2 pieces", grams: 30, kcal: 150, carb: 18, protein: 2, fat: 8, fibre: 0,
        verdict: "driver", note: "Fermented flour batter, deep fried in a spiral so the surface area is maximised for soaking." },
      { name: "Sugar syrup absorbed", qty: "—", grams: 40, kcal: 160, carb: 40, protein: 0, fat: 0, fibre: 0,
        verdict: "driver", note: "The soak is the entire point of the dish. It is also forty grams of sugar." },
    ],
    tiers: [
      { level: 1, label: "One piece, after a meal", saves: 155, tasteCost: "None",
        change: "One, and never on an empty stomach.",
        why: "Sugar on an empty stomach spikes harder and leaves you hungrier. After protein, it does considerably less." },
      { level: 2, label: "Share it", saves: 230, tasteCost: "None",
        change: "Order one plate for the table rather than one each.",
        why: "Jalebi is intense. Two bites deliver most of what four bites do." },
      { level: 3, label: "Change the occasion", saves: 310, tasteCost: "None to the dish",
        change: "Festivals and weddings, not a Sunday habit.",
        why: "There is no lighter jalebi. Frequency is the only honest lever, and pretending otherwise is how these sites lose credibility." },
    ],
  },
  {
    id: "besan-ladoo", name: "Besan ladoo", category: "sweet", veg: true, verified: false, image: null,
    portion: "2 pieces, ~60 g",
    headline: "Two small balls, three hundred and fifty calories. The ghee is why they taste like that.",
    components: [
      { name: "Besan", qty: "—", grams: 25, kcal: 90, carb: 12, protein: 5, fat: 2, fibre: 2,
        verdict: "good", note: "Gram flour has genuine protein and fibre. It is the only redeeming thing here." },
      { name: "Ghee", qty: "—", grams: 20, kcal: 180, carb: 0, protein: 0, fat: 20, fibre: 0,
        verdict: "driver", note: "Roughly half the calories. Roasting besan in ghee is what creates the flavour, so this is not removable without changing the sweet." },
      { name: "Sugar", qty: "—", grams: 20, kcal: 80, carb: 20, protein: 0, fat: 0, fibre: 0,
        verdict: "driver", note: "Straightforward." },
    ],
    tiers: [
      { level: 1, label: "One, and know what it costs", saves: 175, tasteCost: "None",
        change: "One ladoo, not two. Most people eat three without noticing.",
        why: "These are small and dense, which is exactly why the count gets away from people. One is 175 calories." },
      { level: 2, label: "Make them smaller", saves: 175, tasteCost: "None",
        change: "Half-size ladoo at home.",
        why: "The satisfaction of a ladoo is largely in eating a whole one. Two small ones beat one large one for most people." },
      { level: 3, label: "Reduce the sugar", saves: 60, tasteCost: "Moderate",
        change: "Two thirds the sugar, and a little jaggery for depth.",
        why: "Besan ladoo tolerates less sugar better than most Indian sweets because the roasted flour carries so much flavour." },
    ],
  },

  /* ---------------- BASELINE ---------------- */
  {
    id: "khichdi", name: "Khichdi", category: "baseline", veg: true, verified: false, image: null,
    portion: "One plate, ~300 g cooked",
    headline: "Rice and dal cooked together. The only dish here where the ghee is arguably earning its place.",
    components: [
      { name: "Rice", qty: "~60 g dry", grams: 60, kcal: 210, carb: 46, protein: 4, fat: 1, fibre: 1,
        verdict: "neutral", note: "The bulk. Standard portion, no complaints." },
      { name: "Moong dal", qty: "~40 g dry", grams: 40, kcal: 140, carb: 24, protein: 10, fat: 1, fibre: 5,
        verdict: "good", note: "Ten grams of protein and five of fibre. Rice and dal together form a complete protein, which is why this combination has survived three thousand years." },
      { name: "Ghee", qty: "1 tbsp", grams: 13, kcal: 115, carb: 0, protein: 0, fat: 13, fibre: 0,
        verdict: "neutral", note: "Aids absorption of the fat-soluble vitamins in the vegetables and makes the dish tolerable. Worth it here in a way it is not in most dishes." },
    ],
    tiers: [
      { level: 1, label: "Add vegetables and curd", saves: 0, tasteCost: "None",
        change: "Carrot, peas and beans in the khichdi, a katori of curd alongside.",
        why: "This dish is already well built. Vegetables add fibre for almost nothing, and curd rounds out the protein." },
      { level: 2, label: "Shift the ratio", saves: 35, tasteCost: "None",
        change: "Equal rice and dal rather than three to two.",
        why: "More protein, more fibre, marginally fewer calories, and it holds you longer." },
      { level: 3, label: "Change the grain", saves: 40, tasteCost: "Low",
        change: "Millet or broken wheat khichdi.",
        why: "Bajra and jowar khichdi are traditional in large parts of India and considerably higher in fibre." },
    ],
  },
];
